services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ../:/app
    env_file:
      - .env.example
    depends_on:
      - db
    restart: on-failure  # Reinício automático se o container falhar

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: voiceguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
