version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - infra/.env.example
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: voiceguard_user
      POSTGRES_PASSWORD: voiceguard_pass
      POSTGRES_DB: voiceguard_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
