"""✨ Adiciona campo two_factor_enabled ao modelo User

Revision ID: 4e60077d4731
Revises: ad96ec1bde71
Create Date: 2025-07-22 19:19:36.797129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e60077d4731'
down_revision = 'ad96ec1bde71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_factor_enabled')

    # ### end Alembic commands ###
