name: VoiceGuard CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Executar testes
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q

