name: Atualiza Documentação Centralizada

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Gerar documentação centralizada
        run: |
          source venv/bin/activate
          python scripts/gerar_documentacao_centralizada.py

      - name: Commit e push da documentação atualizada
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/Documentacao_Centralizada_*.md
          git commit -m "📚 Atualiza documentação centralizada automática [skip ci]" || echo "Nada para commitar"
          git push origin main
