name: Validar Ambiente VoiceGuard

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - '.env'
      - 'scripts/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências Python
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Executar verificação do .env
        run: |
          python3 scripts/check_env.py || exit 1

      - name: Testar ligação à base de dados
        run: |
          python3 scripts/check_db_connection.py || exit 1
